config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  resources :books do 
  	resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: [:show]

	def index
		@book_lists = Book.all.order(:created_at)
	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		if @book.save!
			redirect_to root_path
		else
			render @book
		end
	end

	def show
	end

	private
	def book_params
		params.require(:book).permit(:title, :author)
	end

	def find_book
		@book = Book.find(params[:id])
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_book

	def new 
		@review = Review.new
	end

	def create
		@review = Review.new(review_params)
		@review.book_id = @book.id
		if @review.save
			redirect_to book_path(@book)
		else
			render 'new'
		end

	end

	private

	def review_params
		params.require(:review).permit(:rating, :comment)
	end

	def find_book
		@book = Book.find(params[:book_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
	<div class="form-group row pb-4">
		<label>Title</label>
    <div>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
  </div>
	<div class="form-group row pb-4">
		<label>Author</label>
    <div>
			<%= f.text_field :author, class: 'form-control' %>
		</div>
  </div>
	<%= f.submit :Submit, class: 'btn btn-primary pt-2' %>
<% end %>

app/views/books/index.html.erb
<div class="container p-5">
	<div style="display: inline-block;" class="pb-4">
		<h3 class="pb-5">Book List</h3>
		Sort by <select name="cars" id="cars">
		  <option value="title">Title</option>
		  <option value="author">Author</option>
		</select>
	</div>
	<table class="mb-5">
		<thead>
			<th class="px-3">Id</th>
			<th class="px-3">Title</th>
			<th class="px-5">Author</th>
		</thead>
		<tbody>
			<% @book_lists.each do |book| %>
				<tr>
					<td class='py-2 px-3'><%= book.id %></td>
					<td class='py-2 px-3'>
						<%= link_to book.title, book_path(book) %>
					</td>
					<td class="py-2 px-5">
						<%= book.author %>
					</td>
				</tr>
			<% end %>
			</tbody>
	</table>

<%= link_to "Add Book", new_book_path %>
</div>

app/views/books/new.html.erb
<div class="container p-5">
	<h3 class="pb-5">Add new book</h3>
	<%= render 'form' %>
	<p class="pt-5"><%= link_to "Book List", '/' %></p>
</div>

app/views/books/show.html.erb
<div class="container py-5">
	<h3 class="pb-3"> Book details </h3>
	<h5>Title: <%= @book.title %></h5>
	<p class="pb-3">Author: <%= @book.author %></p>

	<%# Add review here %>
	<% if @book.reviews.present? %>
		<% @book.reviews.each do |review| %>
			<div class="review-rating" data-score="<%= review.rating %>"></div>
			<%= review.comment %>
			<p>Review on <%= Time.at(review.created_at) %></p>
		<% end %>
	<% end %>
	<br>
	<p class="py-4">
		<%= link_to "Add Review", new_book_review_path(@book)%>
		<%= link_to "Book List", '/', class: 'px-4' %>
	</p>
</div>

<script>
	$(document).ready(function(){
		$('.review-rating').raty({
			readOnly: true,
			score: function(){
				return $(this).attr('data-score');
			},
			path: '/assets/'
		});
	})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookreview</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for [@book, @book.reviews.build] do |f| %>
	<div id="rating-form">Rating:  </div><br><br>
	<div class="form-group row pb-4" id="comment_row" style="display:none">
		<label>Comment:</label>
    <div>
			<%= f.text_field :comment, class: 'form-control' %>
		</div>
  </div>
	<%= f.submit :Submit, class: 'btn btn-primary pt-2' %>
<% end %>

<script>
	$('#rating-form').on('click',function(){
		if($("input[name='review[rating]']").val() >2){
			$('#comment_row').show();
		}
	})
	$('#rating-form').raty({
		path: '/assets/',
		scoreName: 'review[rating]'
	});
</script>

app/views/reviews/new.html.erb
<div class="container pt-5">
	<h4 class="pb-3 pt-5">Add rating</h4>
	<%= render 'form' %>
</div>